version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: judge0/api:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "80:3000"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/api:latest
    command: ["./build_scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  mysql:
    image: mysql:5.7
    env_file: judge0-api.conf
    volumes:
    - ./sql_executors/support_resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    - db_data:/var/lib/mysql
    expose:
      - "3306"
    restart: always
  
  db:
    image: postgres:9.6
    env_file: judge0.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - ./srv/redis-data:/data
    <<: *default-logging
    restart: always
